"""empty message

Revision ID: 099f3e735e6c
Revises: a96ae7dcf6eb
Create Date: 2026-02-03 02:11:38.018575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099f3e735e6c'
down_revision: Union[str, Sequence[str], None] = 'a96ae7dcf6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wishes_user_added_id_fkey'), 'wishes', type_='foreignkey')
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.create_foreign_key(op.f('wishes_user_added_id_fkey'), 'wishes', 'user', ['user_added_id'], ['id'])
    # ### end Alembic commands ###
