"""empty message

Revision ID: 5a1940d22f62
Revises: 
Create Date: 2026-03-29 17:26:24.220985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1940d22f62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('image', sa.String(), nullable=True))
    op.alter_column('wishes', 'user_added_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('wishes_couple_id_fkey'), 'wishes', type_='foreignkey')
    op.drop_constraint(op.f('wishes_user_added_id_fkey'), 'wishes', type_='foreignkey')
    op.create_foreign_key(None, 'wishes', 'couples', ['couple_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.create_foreign_key(op.f('wishes_user_added_id_fkey'), 'wishes', 'user', ['user_added_id'], ['id'])
    op.create_foreign_key(op.f('wishes_couple_id_fkey'), 'wishes', 'couples', ['couple_id'], ['id'])
    op.alter_column('wishes', 'user_added_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('wishes', 'image')
    # ### end Alembic commands ###
