"""empty message

Revision ID: 5c111c8e4c2a
Revises: 099f3e735e6c
Create Date: 2026-02-03 02:17:37.259879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c111c8e4c2a'
down_revision: Union[str, Sequence[str], None] = '099f3e735e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishes', 'user_added_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('wishes_user_added_id_fkey'), 'wishes', type_='foreignkey')
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.create_foreign_key(op.f('wishes_user_added_id_fkey'), 'wishes', 'user', ['user_added_id'], ['id'], ondelete='CASCADE')
    op.alter_column('wishes', 'user_added_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
