"""empty message

Revision ID: 77a8baad8b14
Revises: 3b250e5e2a18
Create Date: 2026-01-09 09:58:29.267733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a8baad8b14'
down_revision: Union[str, Sequence[str], None] = '3b250e5e2a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('user_added_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_column('wishes', 'user_added_id')
    # ### end Alembic commands ###
