"""empty message

Revision ID: a96ae7dcf6eb
Revises: 595692e09ea8
Create Date: 2026-02-03 02:05:37.827571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96ae7dcf6eb'
down_revision: Union[str, Sequence[str], None] = '595692e09ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wishes_couple_id_fkey'), 'wishes', type_='foreignkey')
    op.create_foreign_key(None, 'wishes', 'couples', ['couple_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.create_foreign_key(op.f('wishes_couple_id_fkey'), 'wishes', 'couples', ['couple_id'], ['id'])
    # ### end Alembic commands ###
