"""empty message

Revision ID: aa64a6679833
Revises: 5c111c8e4c2a
Create Date: 2026-02-04 00:52:57.081271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa64a6679833'
down_revision: Union[str, Sequence[str], None] = '5c111c8e4c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wishes_user_added_id_fkey'), 'wishes', type_='foreignkey')
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.create_foreign_key(op.f('wishes_user_added_id_fkey'), 'wishes', 'user', ['user_added_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
