"""empty message

Revision ID: 3b250e5e2a18
Revises: 37d3f0ac4893
Create Date: 2026-01-09 09:54:54.095336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b250e5e2a18'
down_revision: Union[str, Sequence[str], None] = '37d3f0ac4893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('article', sa.Integer(), nullable=False))
    op.add_column('wishes', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'url')
    op.drop_column('wishes', 'article')
    # ### end Alembic commands ###
