"""empty message

Revision ID: 595692e09ea8
Revises: a08be3fbd285
Create Date: 2026-02-01 23:54:24.085521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595692e09ea8'
down_revision: Union[str, Sequence[str], None] = 'a08be3fbd285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'image')
    # ### end Alembic commands ###
