"""empty message

Revision ID: 9084a583939d
Revises: eb590a0ae57d
Create Date: 2026-07-29 22:50:07.877491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9084a583939d'
down_revision: Union[str, Sequence[str], None] = 'eb590a0ae57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("""
            DELETE FROM wishes 
            WHERE user_added_id IS NOT NULL 
            AND user_added_id NOT IN (SELECT id FROM "user")
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    # ### end Alembic commands ###
