"""empty message

Revision ID: eb590a0ae57d
Revises: 374051d561ab
Create Date: 2026-07-29 02:01:08.847133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb590a0ae57d'
down_revision: Union[str, Sequence[str], None] = '374051d561ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_foreign_key(None, 'wishes', 'user', ['user_added_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
